// Code generated by paladin. DO NOT EDIT.

package dbc

import (
	"encoding/json"
	"fmt"
	"os"
)

type Exchange struct {
	Id      int64
	Name    string
	Count   int32
	Gp      int32
	Diamond int64
	Exp     int32
	Score   int32
	Skin    int64
}

var tblExchange map[int64]*Exchange

func GetExchange(id int64) *Exchange {
	return tblExchange[id]
}

func GetAllExchange() map[int64]*Exchange {
	return tblExchange
}

func init() {
	file, err := os.Open("data/exchange.json")
	if err != nil {
		fmt.Println("fail to open!!", err)
		return
	}
	defer file.Close()
	decoder := json.NewDecoder(file)
	err = decoder.Decode(&tblExchange)
	if err != nil {
		fmt.Println("fail to decode!!", err)
		return
	}
}
