// Code generated by paladin. DO NOT EDIT.

package dbc

import (
	"encoding/json"
	"fmt"
	"os"
)

type Exp struct {
	Id         int64
	Name       string
	Level      int32
	TotalExp   int32
	PromoteExp int32
}

var tblExp map[int64]*Exp

func GetExp(id int64) *Exp {
	return tblExp[id]
}

func GetAllExp() map[int64]*Exp {
	return tblExp
}

func init() {
	file, err := os.Open("data/exp.json")
	if err != nil {
		fmt.Println("fail to open!!", err)
		return
	}
	defer file.Close()
	decoder := json.NewDecoder(file)
	err = decoder.Decode(&tblExp)
	if err != nil {
		fmt.Println("fail to decode!!", err)
		return
	}
}
