// Code generated by paladin. DO NOT EDIT.

package dbc

import (
	"encoding/json"
	"fmt"
	"os"
)

type Global struct {
	Id             int64
	InviteBonus    int64
	ShareCntMax    int64
	ShareBonus     int64
	RecvPresentMax int64
	OppoListMax    int64
	InitGold       int64
	InitDiamond    int64
	AdBonus        int64
}

var tblGlobal map[int64]*Global

func GetGlobal(id int64) *Global {
	return tblGlobal[id]
}

func GetAllGlobal() map[int64]*Global {
	return tblGlobal
}

func init() {
	file, err := os.Open("data/global.json")
	if err != nil {
		fmt.Println("fail to open!!", err)
		return
	}
	defer file.Close()
	decoder := json.NewDecoder(file)
	err = decoder.Decode(&tblGlobal)
	if err != nil {
		fmt.Println("fail to decode!!", err)
		return
	}
}
