// Code generated by paladin. DO NOT EDIT.

package dbc

import (
	"encoding/json"
	"fmt"
	"os"
)

type PackDice struct {
	DiceSkin int64
	Chance   int64
}

type PackTheme struct {
	ThemeSkin int64
	Chance    int64
}

type Pack struct {
	Id    int64
	Name  string
	Desc  string
	Dice  []PackDice
	Theme []PackTheme
}

var tblPack map[int64]*Pack

func GetPack(id int64) *Pack {
	return tblPack[id]
}

func GetAllPack() map[int64]*Pack {
	return tblPack
}

func init() {
	file, err := os.Open("data/pack.json")
	if err != nil {
		fmt.Println("fail to open!!", err)
		return
	}
	defer file.Close()
	decoder := json.NewDecoder(file)
	err = decoder.Decode(&tblPack)
	if err != nil {
		fmt.Println("fail to decode!!", err)
		return
	}
}
