// Code generated by paladin. DO NOT EDIT.

package dbc

import (
	"encoding/json"
	"fmt"
	"os"
)

type Skin struct {
	Id         int64
	Name       string
	Desc       string
	Type       int64
	Gp         int64
	Diamond    int64
	BonusType  int64
	BonusValue int64
	Task       bool
	Expire     int64
	RelateId   int64
}

var tblSkin map[int64]*Skin

func GetSkin(id int64) *Skin {
	return tblSkin[id]
}

func GetAllSkin() map[int64]*Skin {
	return tblSkin
}

func init() {
	file, err := os.Open("data/skin.json")
	if err != nil {
		fmt.Println("fail to open!!", err)
		return
	}
	defer file.Close()
	decoder := json.NewDecoder(file)
	err = decoder.Decode(&tblSkin)
	if err != nil {
		fmt.Println("fail to decode!!", err)
		return
	}
}
