// Code generated by paladin. DO NOT EDIT.

package dbc

import (
	"encoding/json"
	"fmt"
	"os"
)

type Task struct {
	Id       int64
	Name     string
	TaskType int64
	TaskMode int32
	Param    int64
	Param2   int64
	Gold     int64
	Diamond  int64
	Exp      int32
	Score    int32
	Gp       int32
	Skin     int64
}

var tblTask map[int64]*Task

func GetTask(id int64) *Task {
	return tblTask[id]
}

func GetAllTask() map[int64]*Task {
	return tblTask
}

func init() {
	file, err := os.Open("data/task.json")
	if err != nil {
		fmt.Println("fail to open!!", err)
		return
	}
	defer file.Close()
	decoder := json.NewDecoder(file)
	err = decoder.Decode(&tblTask)
	if err != nil {
		fmt.Println("fail to decode!!", err)
		return
	}
}
