// Code generated by paladin. DO NOT EDIT.
using System;
using System.Collections.Generic;

namespace Dbc {

	[Serializable]
	public class Exchange {
		public long Id;
		public string Name;
		public int Count;
		public int Gp;
		public long Diamond;
		public int Exp;
		public int Score;
		public long Skin;
	}
}