// Code generated by paladin. DO NOT EDIT.
using System;
using System.Collections.Generic;

namespace Dbc {

	[Serializable]
	public class Exp {
		public long Id;
		public string Name;
		public int Level;
		public int TotalExp;
		public int PromoteExp;
	}
}