// Code generated by paladin. DO NOT EDIT.
using System;
using System.Collections.Generic;

namespace Dbc {

	[Serializable]
	public class Gift {
		public long Id;
		public string Name;
		public long Charm;
		public long CostGold;
		public long CostDiamond;
		public long Priority;
	}
}