// Code generated by paladin. DO NOT EDIT.
using System;
using System.Collections.Generic;

namespace Dbc {

	[Serializable]
	public class Global {
		public long Id;
		public long InviteBonus;
		public long ShareCntMax;
		public long ShareBonus;
		public long RecvPresentMax;
		public long OppoListMax;
		public long InitGold;
		public long InitDiamond;
		public long AdBonus;
	}
}
		public long InitDiamond;
		public long AdBonus;
		public long AdBonusCount;
		public long PresentGold;
		public long WinExp1v1;
		public long WinExp2v2;
		public long WinExp4Rank1;
		public long WinExp4Rank2;
		public long WinScore;
		public long RobotChipMax;
		public long MatchGameTime;
		public long BindFbBonus;
		public long ChanllengerStarScore;
		public long InviteCnt;
		public long BankruptBonus;
		public long BankruptCnt;
		public long GenderMatchDiamond;
		public long TaskVersion;
	}
}