// Code generated by paladin. DO NOT EDIT.
using System;
using System.Collections.Generic;

namespace Dbc {

	[Serializable]
	public class PackDice {
		public long DiceSkin;
		public long Chance;
	}

	[Serializable]
	public class PackTheme {
		public long ThemeSkin;
		public long Chance;
	}

	[Serializable]
	public class Pack {
		public long Id;
		public string Name;
		public string Desc;
		public List<PackDice> Dice;
		public List<PackTheme> Theme;
	}
}