// Code generated by paladin. DO NOT EDIT.
using System;
using System.Collections.Generic;

namespace Dbc {

	[Serializable]
	public class Room {
		public long Id;
		public string Name;
		public long Level;
		public long RoomType;
		public long GameType;
		public long BootAmount;
		public long EnterMin;
		public long EnterMax;
		public int MaxBlind;
		public long ChaalLimit;
		public long PotLimit;
		public long TipAmount;
	}
}