// Code generated by paladin. DO NOT EDIT.
using System;
using System.Collections.Generic;

namespace Dbc {

	[Serializable]
	public class Score {
		public long Id;
		public string Name;
		public long Dan;
		public long SubDan;
		public long DanStar;
		public long TotalScore;
		public long PromoteScore;
		public long LevelScore;
	}
}