// Code generated by paladin. DO NOT EDIT.
using System;
using System.Collections.Generic;

namespace Dbc {

	[Serializable]
	public class Shop {
		public long Id;
		public string Name;
		public string Desc;
		public string ProductId;
		public int Flag;
		public long DollarCent;
		public string Icon;
		public long Gold;
		public long Diamond;
		public long GoldBonus;
		public long Pack;
	}
}