// Code generated by paladin. DO NOT EDIT.
using System;
using System.Collections.Generic;

namespace Dbc {

	[Serializable]
	public class Skin {
		public long Id;
		public string Name;
		public string Desc;
		public long Type;
		public long Gp;
		public long Diamond;
		public long BonusType;
		public long BonusValue;
		public bool Task;
		public long Expire;
		public long RelateId;
	}
}