// Code generated by paladin. DO NOT EDIT.
using System;
using System.Collections.Generic;

namespace Dbc {

	[Serializable]
	public class Task {
		public long Id;
		public string Name;
		public long TaskType;
		public int TaskMode;
		public long Param;
		public long Param2;
		public long Gold;
		public long Diamond;
		public int Exp;
		public int Score;
		public int Gp;
		public long Skin;
	}
}